title: "AZINUDDIN AZLANI"
description: "<strong>Software & AI Engineer</strong>"
tagline: "Azinuddin Azlani - Software & AI Engineer"
logo: "/assets/images/profile.JPG"
theme: jekyll-theme-minimal
show_downloads: false
# google_analytics: # Add your tracking ID if you want analytics
plugins:
  - jekyll-seo-tag

  # Contact information for sidebar
contact:
  location: "Bangsar, Kuala Lumpur"
  linkedin: "https://www.linkedin.com/in/azinuddinazlani/"
  github: "https://github.com/azinuddinazlani"

# Professional summary for sidebar
summary: "Software & AI Engineer with experience in platform support and technical troubleshooting. Skilled in Python, Kubernetes, and cloud technologies. Recently completed Full Stack Software Development certification with focus on AI applications."